name: Build and Deploy to Gatsby every two hours

on:
  push

jobs:
  build:
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest

    steps:
      # Check out the current repository code
      - uses: actions/checkout@v1
      
      - name: Set up node using nvm
          # You may pin to the exact commit or the version.
          # uses: dcodeIO/setup-node-nvm@67e33081918632dcbba53dbc5484ee124e4dd8f4
        uses: dcodeIO/setup-node-nvm@v4
        
      - name: Read .nvmrc
        # You may pin to the exact commit or the version.
        # uses: browniebroke/read-nvmrc-action@377268bc49bb9ea619bcf2e504c85805e6bab267
        uses: browniebroke/read-nvmrc-action@v1

      - run: yarn install
      
      # This triggers `gatsby build` script in "package.json"
      - run: yarn run build
      
      # 4. Deploy the gatsby build to Netlify
      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          # 5. "gatsby build" creates "public" folder, which is what we are deploying
          args: deploy --dir=public --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
